[package]
name = "learn-web3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
hex = "0.4"
tokio = { versions = "1", features = ["full"] }
web3 = "0.17.0"
